repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0 # keep in sync with tests/lint_requirements.txt
    hooks:
      - id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1  # keep in sync with tests/lint_requirements.txt
    hooks:
      - id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1  # keep in sync with tests/lint_requirements.txt
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.7.0]
