repos:
-   repo: https://github.com/ambv/black
    rev: 21.8b0  # keep in sync with tests/lint_requirements.txt
    hooks:
      - id: black
        language_version: python3.8
    - id: black
      language_version: python3
-   repo: https://github.com/timothycrosley/isort
    rev: '5.9.3'  # keep in sync with tests/lint_requirements.txt
    hooks:
    -   id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'  # keep in sync with tests/lint_requirements.txt
    hooks:
    -   id: flake8
-   repo: https://github.com/ikamensh/flynt
    rev: '0.66'  # keep in sync with tests/lint_requirements.txt
    hooks:
    -   id: flynt
